### ISSUE TITLE
Problem with Model State

### ISSUE THREAD

**Issue by mpaul31** [brockallen/CookieTempData#2]
Hello,

I am having trouble storing the ModelState using the following provider. Is this supported?

I use it to export model state when performing a redirect, which seems to be a very popular pattern in the community.

thanks!

**Comment by brockallen** [comment]
Is ModelState serializable? I'd suggest storing simple data structures since they need to be serialized.

**Comment by mpaul31** [comment]
System.Web.Mvc.ModelStateDictionary is serializable.

Here is the pattern I and many others use:
http://craigsdevspace.wordpress.com/2011/11/06/prg-pattern-how-to-keep-mvc-modelstate/

**Comment by brockallen** [comment]
Well, CookieTempData uses the BinarySerializer to save your state. If you can put ModelState into the BinarySerializer and less than the size of a cookie then you're good to go. I'd suggest debugging further what the issue is and report back. If there's something I can help fix, I will, but I need you to help discover the real problem or bug for your situation.

**Comment by brockallen** [comment]
I just tried this and it works fine. I even updated the sample to show it working: https://github.com/brockallen/CookieTempData/commit/28d11f8f994b642bc46d06b38e3b7d3cc6970827

**Comment by brockallen** [comment]
The one thing you might run into is the amount of data that's put into the cookie. If the data exceeds 4K then the browser won't send it back and you will lose the data. So keep in mind that TempData (and Cookies) are meant for a small amount of data. If you're finding the cookie size is too large, then consider using a different data structure other than ModelState.
